apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: karlaru.com
spec:
  api:
    dns: {}
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://karl-aru-mb-state/karlaru.com
  etcdClusters:
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-north-1b
      name: b
      volumeSize: 1
    memoryRequest: 50Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - encryptedVolume: true
      instanceGroup: master-eu-north-1b
      name: b
      volumeSize: 1
    memoryRequest: 50Mi
    name: events
  iam:
    serviceAccountExternalPermissions:
      - name: iam-account
        namespace: default
        aws:
          inlinePolicy: |-
            [
              {
                "Effect": "Allow",
                "Action": [
                    "s3:PutObject",
                    "dynamodb:PutItem",
                    "dynamodb:DeleteItem",
                    "dynamodb:GetItem",
                    "dynamodb:Scan"
                ],
                "Resource": [
                    "arn:aws:s3:::karlaru-mb/*",
                    "arn:aws:dynamodb:eu-north-1:978039897892:table/messages",
                    "arn:aws:dynamodb:eu-north-1:978039897892:table/users"
                ]
              }
            ]
  certManager:
    enabled: true
  podIdentityWebhook:
    enabled: true
  kubelet:
    anonymousAuth: false
  kubernetesApiAccess:
  - 88.196.254.0/24
  kubernetesVersion: 1.23.9
  masterPublicName: api.karlaru.com
  networkCIDR: 10.0.0.0/20
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.0.0.0/20
  serviceAccountIssuerDiscovery:
    discoveryStore: s3://karlaru-mb-oidc/karlaru.com/discovery/karlaru.com
    enableAWSOIDCProvider: true
  subnets:
  - cidr: 10.0.0.0/24
    name: eu-north-1b
    type: Public
    zone: eu-north-1b
  topology:
    dns:
      type: Public
    masters: private
    nodes: private

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-06-13T18:19:26Z"
  generation: 3
  labels:
    kops.k8s.io/cluster: karlaru.com
  name: master-eu-north-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220609
  instanceMetadata:
    httpPutResponseHopLimit: 3
    httpTokens: required
  machineType: t3.small
  maxPrice: "0.022"
  maxSize: 1
  minSize: 1
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-north-1b
    lifecycle: spot
  role: Master
  rootVolumeSize: 8
  rootVolumeType: gp3
  subnets:
  - eu-north-1b

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2022-06-13T18:19:26Z"
  generation: 21
  labels:
    kops.k8s.io/cluster: karlaru.com
  name: nodes-eu-north-1b
spec:
  image: 099720109477/ubuntu/images/hvm-ssd/ubuntu-jammy-22.04-amd64-server-20220609
  instanceMetadata:
    httpPutResponseHopLimit: 1
    httpTokens: required
  machineType: t3.micro
  maxPrice: "0.012"
  maxSize: 2
  minSize: 2
  nodeLabels:
    kops.k8s.io/instancegroup: nodes-eu-north-1b
    lifecycle: spot
  role: Node
  rootVolumeSize: 8
  rootVolumeType: gp3
  subnets:
  - eu-north-1b
