apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-mb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: 50m

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - karlaru.com
      secretName: main-tls
  rules:
    - host: karlaru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: messageboard
                port:
                  number: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-docs
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/configuration-snippet: |
      add_header X-Frame-Options 'sameorigin';
      add_header X-Content-Type-Options 'nosniff';
      add_header Referrer-Policy 'strict-origin-when-cross-origin';

spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - docs.karlaru.com
      secretName: main-tls
  rules:

    - host: docs.karlaru.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port:
                  number: 3000
